version: '3.3'
services:
    redis:
      image: "redis:latest"
      ports:
        - "6379:6379"

    eureka:
      build:
        context: ./eureka
      ports:
        - "8080:8761"

    gateway:
      build:
        context: ./gateway
      depends_on:
        - eureka

    kino_service:
      build:
        context: ./kino-service
      depends_on:
        - eureka
