version: '3.3'
services:
    redis:
      image: "redis:latest"
    eureka:
      build:
        context: ./eureka

    gateway:
      build:
        context: ./gateway
      ports:
        - "8080:8080"
      depends_on:
        - eureka

    kino_service:
      build:
        context: ./kino-service
      depends_on:
        - eureka

    ticket_service:
      build:
        context: ./ticket-service
      depends_on:
        - eureka

    user_service:
      build:
        context: ./user-service
      depends_on:
        - eureka
