version: '3.3'
services:
    redis:
      image: "redis:latest"
      ports:
        - "6379:6379"
    #serviceName:
        #build:
            #context: ./moduleFolderName
            #dockerfile: Dockerfile
        #ports:
        # - "externalPort":"containerPort"
        #depends_on:
        # - "serviceName of dependency"
