version: '3.3'
services:
    redis:
      image: "redis:latest"
      ports:
        - "6379:6379"

    eureka:
      build:
        context: ./eureka

    gateway:
      build:
        context: ./gateway
      ports:
        - "8080:8080"
      depends_on:
        - eureka

    kino_service:
      build:
        context: ./kino-service
      depends_on:
        - eureka
