spring:
  redis:
    #host: redis
    host: localhost
    port: 6379
  session:
    # specify that session tokes should be stored in Redis
    store-type: redis
  application:
    name: kino-service
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/