spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        # "lb" stands for Load-Balance, which is done with Ribbon
        uri: lb://user-service
        predicates:
        - Path=/users/**
        filters:
        - StripPrefix=1
      - id: kino-service
        uri: lb://kino-service
        predicates:
        - Path=/kino/**
        filters:
        - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/