spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        # "lb" stands for Load-Balance, which is done with Ribbon
        uri: lb://user-service
        predicates:
        - Path=/api/v1/users/**
        filters:
        - StripPrefix=2
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/api/v1/auth/**
        filters:
        - StripPrefix=2
      - id: kino-service
        uri: lb://kino-service
        predicates:
        - Path=/api/v1/kino/**
        filters:
        - StripPrefix=3
      - id: ticket-service
        uri: lb://ticket-service
        predicates:
        - Path=/api/v1/tickets/**
        filters:
        - StripPrefix=2
      - id: movie-service
        uri: lb://movie-service
        predicates:
        - Path=/api/v1/movies/**
        filters:
        - StripPrefix=2

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/