spring:
  application:
    name: movie-service

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
logging:
  level:
    org.springframework.security: debug
---
spring:
  profiles:
    active:
    - local
  port: 8087
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: h2
eureka:
  client:
    enabled: false